name: Build LaTeX document
on:
  push:
    branches:
    - main
    - release/*
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "src"
          root_file: "*.tex"
          glob_root_file: true
          continue_on_error: true
          extra_system_packages: "listings xcolor babel bookman inputenx fontenc xspace lastpage fancyhdr tabularx tikz ulem varioref url moreverb ifthen amsmath siunitx color mhchem geometry esint mathdesign"
          pre_compile: "tlmgr update --self && tlmgr update --all"
          post_compile: "latexmk -c"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: guidelines.pdf
