name: Build LaTeX document
on:
  push:
    branches:
    - main
    - release/*
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          root_file: latest.tex
          continue_on_error: true
      - name: Upload PDF file
        uses: actions/upload-artifact@master
        with:
          name: latest.pdf
          path: ./dist/
        if: always()